---
framework: jest
preRun:
     command:
        - yarn install --immutable
        - yarn lint
        - yarn test:types
        - yarn run build
preMerge:
  pattern:
    - "./test/*.js"
  env:
    NODE_ENV: test
postMerge:
  pattern:
    - "./test/*.js"
  env:
    NODE_ENV: test
postRun:
     command:
        - yarn --version
version: 1.0
